//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS_Application.QLNVServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QLNVServiceReference.IQLNS_Service")]
    public interface IQLNS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/NhanVien", ReplyAction="http://tempuri.org/IQLNS_Service/NhanVienResponse")]
        System.Data.DataSet NhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/NhanVien", ReplyAction="http://tempuri.org/IQLNS_Service/NhanVienResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> NhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/NguoiDung", ReplyAction="http://tempuri.org/IQLNS_Service/NguoiDungResponse")]
        System.Data.DataSet NguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/NguoiDung", ReplyAction="http://tempuri.org/IQLNS_Service/NguoiDungResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> NguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/ktDangNhap", ReplyAction="http://tempuri.org/IQLNS_Service/ktDangNhapResponse")]
        bool ktDangNhap(string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQLNS_Service/ktDangNhap", ReplyAction="http://tempuri.org/IQLNS_Service/ktDangNhapResponse")]
        System.Threading.Tasks.Task<bool> ktDangNhapAsync(string UID, string PWD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQLNS_ServiceChannel : QLNS_Application.QLNVServiceReference.IQLNS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLNS_ServiceClient : System.ServiceModel.ClientBase<QLNS_Application.QLNVServiceReference.IQLNS_Service>, QLNS_Application.QLNVServiceReference.IQLNS_Service {
        
        public QLNS_ServiceClient() {
        }
        
        public QLNS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLNS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLNS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLNS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet NhanVien() {
            return base.Channel.NhanVien();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NhanVienAsync() {
            return base.Channel.NhanVienAsync();
        }
        
        public System.Data.DataSet NguoiDung() {
            return base.Channel.NguoiDung();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NguoiDungAsync() {
            return base.Channel.NguoiDungAsync();
        }
        
        public bool ktDangNhap(string UID, string PWD) {
            return base.Channel.ktDangNhap(UID, PWD);
        }
        
        public System.Threading.Tasks.Task<bool> ktDangNhapAsync(string UID, string PWD) {
            return base.Channel.ktDangNhapAsync(UID, PWD);
        }
    }
}
